"""add marketplace job postings and agent proposals

Revision ID: 3244cae4e4ee
Revises: 21a05bbbe62b
Create Date: 2026-09-01 19:26:40.983686

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.app.models.base


# revision identifiers, used by Alembic.
revision: str = '3244cae4e4ee'
down_revision: Union[str, None] = '21a05bbbe62b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_postings',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('job_id', sa.String(length=64), nullable=False),
    sa.Column('creator_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('bounty_reward', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('accepted_proposal_id', backend.app.models.base.GUID(), nullable=True),
    sa.Column('task_id', backend.app.models.base.GUID(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_postings_created_at'), 'job_postings', ['created_at'], unique=False)
    op.create_index(op.f('ix_job_postings_creator_id'), 'job_postings', ['creator_id'], unique=False)
    op.create_index(op.f('ix_job_postings_job_id'), 'job_postings', ['job_id'], unique=True)
    op.create_index(op.f('ix_job_postings_status'), 'job_postings', ['status'], unique=False)
    op.create_table('agent_proposals',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('proposal_id', sa.String(length=64), nullable=False),
    sa.Column('job_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('agent_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('proposed_strategy', sa.Text(), nullable=False),
    sa.Column('estimated_duration_seconds', sa.Integer(), nullable=False),
    sa.Column('bid_score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['job_id'], ['job_postings.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_proposals_agent_id'), 'agent_proposals', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_proposals_created_at'), 'agent_proposals', ['created_at'], unique=False)
    op.create_index(op.f('ix_agent_proposals_job_id'), 'agent_proposals', ['job_id'], unique=False)
    op.create_index(op.f('ix_agent_proposals_proposal_id'), 'agent_proposals', ['proposal_id'], unique=True)
    op.create_index(op.f('ix_agent_proposals_status'), 'agent_proposals', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_agent_proposals_status'), table_name='agent_proposals')
    op.drop_index(op.f('ix_agent_proposals_proposal_id'), table_name='agent_proposals')
    op.drop_index(op.f('ix_agent_proposals_job_id'), table_name='agent_proposals')
    op.drop_index(op.f('ix_agent_proposals_created_at'), table_name='agent_proposals')
    op.drop_index(op.f('ix_agent_proposals_agent_id'), table_name='agent_proposals')
    op.drop_table('agent_proposals')
    op.drop_index(op.f('ix_job_postings_status'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_job_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_creator_id'), table_name='job_postings')
    op.drop_index(op.f('ix_job_postings_created_at'), table_name='job_postings')
    op.drop_table('job_postings')
    # ### end Alembic commands ###
