"""initial_schema

Revision ID: 21a05bbbe62b
Revises: 
Create Date: 2026-09-01 12:59:07.546670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import backend.app.models.base


# revision identifiers, used by Alembic.
revision: str = '21a05bbbe62b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=64), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target_type', sa.String(length=32), nullable=True),
    sa.Column('target_id', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_type'), 'audit_logs', ['actor_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_id'), 'audit_logs', ['target_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_target_type'), 'audit_logs', ['target_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_timestamp'), 'audit_logs', ['timestamp'], unique=False)
    op.create_table('users',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_at'), 'users', ['created_at'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('agents',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('owner_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('model_provider', sa.String(length=32), nullable=False),
    sa.Column('model_name', sa.String(length=64), nullable=False),
    sa.Column('capabilities', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('reputation_score', sa.Float(), nullable=False),
    sa.Column('tasks_completed', sa.Integer(), nullable=False),
    sa.Column('successful_tasks', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_created_at'), 'agents', ['created_at'], unique=False)
    op.create_index(op.f('ix_agents_name'), 'agents', ['name'], unique=False)
    op.create_index(op.f('ix_agents_owner_id'), 'agents', ['owner_id'], unique=False)
    op.create_index(op.f('ix_agents_public_id'), 'agents', ['public_id'], unique=True)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_table('tasks',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('task_id', sa.String(length=64), nullable=False),
    sa.Column('creator_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('requirements', sa.JSON(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('result', sa.JSON(), nullable=True),
    sa.Column('max_iterations', sa.Integer(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tasks_created_at'), 'tasks', ['created_at'], unique=False)
    op.create_index(op.f('ix_tasks_creator_id'), 'tasks', ['creator_id'], unique=False)
    op.create_index(op.f('ix_tasks_status'), 'tasks', ['status'], unique=False)
    op.create_index(op.f('ix_tasks_task_id'), 'tasks', ['task_id'], unique=True)
    op.create_table('agent_permissions',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('agent_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('permission_name', sa.String(length=64), nullable=False),
    sa.Column('granted_by', sa.String(length=64), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_permissions_agent_id'), 'agent_permissions', ['agent_id'], unique=False)
    op.create_index(op.f('ix_agent_permissions_permission_name'), 'agent_permissions', ['permission_name'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('task_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('reviewer_agent_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('target_agent_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('task_success_score', sa.Float(), nullable=False),
    sa.Column('usefulness_score', sa.Float(), nullable=False),
    sa.Column('accuracy_score', sa.Float(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('safety_score', sa.Float(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewer_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_created_at'), 'evaluations', ['created_at'], unique=False)
    op.create_index(op.f('ix_evaluations_reviewer_agent_id'), 'evaluations', ['reviewer_agent_id'], unique=False)
    op.create_index(op.f('ix_evaluations_target_agent_id'), 'evaluations', ['target_agent_id'], unique=False)
    op.create_index(op.f('ix_evaluations_task_id'), 'evaluations', ['task_id'], unique=False)
    op.create_table('hives',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('public_id', sa.String(length=64), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('lead_agent_id', backend.app.models.base.GUID(), nullable=True),
    sa.Column('task_id', backend.app.models.base.GUID(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['lead_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hives_created_at'), 'hives', ['created_at'], unique=False)
    op.create_index(op.f('ix_hives_public_id'), 'hives', ['public_id'], unique=True)
    op.create_table('knowledge',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('source_agent_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('task_id', backend.app.models.base.GUID(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('verification_count', sa.Integer(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('failure_count', sa.Integer(), nullable=False),
    sa.Column('visibility', sa.String(length=32), nullable=False),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['source_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_created_at'), 'knowledge', ['created_at'], unique=False)
    op.create_index(op.f('ix_knowledge_source_agent_id'), 'knowledge', ['source_agent_id'], unique=False)
    op.create_index(op.f('ix_knowledge_summary'), 'knowledge', ['summary'], unique=False)
    op.create_index(op.f('ix_knowledge_task_id'), 'knowledge', ['task_id'], unique=False)
    op.create_index(op.f('ix_knowledge_visibility'), 'knowledge', ['visibility'], unique=False)
    op.create_table('reputation_events',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('agent_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('score_delta', sa.Float(), nullable=False),
    sa.Column('new_score', sa.Float(), nullable=False),
    sa.Column('reference_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reputation_events_agent_id'), 'reputation_events', ['agent_id'], unique=False)
    op.create_index(op.f('ix_reputation_events_event_type'), 'reputation_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_reputation_events_timestamp'), 'reputation_events', ['timestamp'], unique=False)
    op.create_table('task_assignments',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('task_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('agent_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('role', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_task_assignments_agent_id'), 'task_assignments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_task_assignments_task_id'), 'task_assignments', ['task_id'], unique=False)
    op.create_table('hive_members',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('hive_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('agent_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('role_in_hive', sa.String(length=64), nullable=False),
    sa.Column('joined_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('left_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hive_id', 'agent_id', name='uq_hive_agent')
    )
    op.create_index(op.f('ix_hive_members_agent_id'), 'hive_members', ['agent_id'], unique=False)
    op.create_index(op.f('ix_hive_members_hive_id'), 'hive_members', ['hive_id'], unique=False)
    op.create_table('knowledge_verifications',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('knowledge_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('verifying_agent_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('verdict', sa.String(length=32), nullable=False),
    sa.Column('evidence', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['knowledge_id'], ['knowledge.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['verifying_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_verifications_knowledge_id'), 'knowledge_verifications', ['knowledge_id'], unique=False)
    op.create_index(op.f('ix_knowledge_verifications_verifying_agent_id'), 'knowledge_verifications', ['verifying_agent_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('message_id', sa.String(length=64), nullable=False),
    sa.Column('sender_agent_id', backend.app.models.base.GUID(), nullable=False),
    sa.Column('recipient_agent_id', backend.app.models.base.GUID(), nullable=True),
    sa.Column('task_id', backend.app.models.base.GUID(), nullable=True),
    sa.Column('hive_id', backend.app.models.base.GUID(), nullable=True),
    sa.Column('message_type', sa.String(length=32), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('raw_content_hash', sa.String(length=64), nullable=False),
    sa.Column('sensitivity', sa.String(length=32), nullable=False),
    sa.Column('authorization_result', sa.String(length=32), nullable=False),
    sa.Column('extra_metadata', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['hive_id'], ['hives.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recipient_agent_id'], ['agents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sender_agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['task_id'], ['tasks.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_hive_id'), 'messages', ['hive_id'], unique=False)
    op.create_index(op.f('ix_messages_message_id'), 'messages', ['message_id'], unique=True)
    op.create_index(op.f('ix_messages_recipient_agent_id'), 'messages', ['recipient_agent_id'], unique=False)
    op.create_index(op.f('ix_messages_sender_agent_id'), 'messages', ['sender_agent_id'], unique=False)
    op.create_index(op.f('ix_messages_task_id'), 'messages', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_task_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_sender_agent_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_recipient_agent_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_message_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_hive_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_knowledge_verifications_verifying_agent_id'), table_name='knowledge_verifications')
    op.drop_index(op.f('ix_knowledge_verifications_knowledge_id'), table_name='knowledge_verifications')
    op.drop_table('knowledge_verifications')
    op.drop_index(op.f('ix_hive_members_hive_id'), table_name='hive_members')
    op.drop_index(op.f('ix_hive_members_agent_id'), table_name='hive_members')
    op.drop_table('hive_members')
    op.drop_index(op.f('ix_task_assignments_task_id'), table_name='task_assignments')
    op.drop_index(op.f('ix_task_assignments_agent_id'), table_name='task_assignments')
    op.drop_table('task_assignments')
    op.drop_index(op.f('ix_reputation_events_timestamp'), table_name='reputation_events')
    op.drop_index(op.f('ix_reputation_events_event_type'), table_name='reputation_events')
    op.drop_index(op.f('ix_reputation_events_agent_id'), table_name='reputation_events')
    op.drop_table('reputation_events')
    op.drop_index(op.f('ix_knowledge_visibility'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_task_id'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_summary'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_source_agent_id'), table_name='knowledge')
    op.drop_index(op.f('ix_knowledge_created_at'), table_name='knowledge')
    op.drop_table('knowledge')
    op.drop_index(op.f('ix_hives_public_id'), table_name='hives')
    op.drop_index(op.f('ix_hives_created_at'), table_name='hives')
    op.drop_table('hives')
    op.drop_index(op.f('ix_evaluations_task_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_target_agent_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_reviewer_agent_id'), table_name='evaluations')
    op.drop_index(op.f('ix_evaluations_created_at'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_agent_permissions_permission_name'), table_name='agent_permissions')
    op.drop_index(op.f('ix_agent_permissions_agent_id'), table_name='agent_permissions')
    op.drop_table('agent_permissions')
    op.drop_index(op.f('ix_tasks_task_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_status'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_creator_id'), table_name='tasks')
    op.drop_index(op.f('ix_tasks_created_at'), table_name='tasks')
    op.drop_table('tasks')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_public_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_owner_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_name'), table_name='agents')
    op.drop_index(op.f('ix_agents_created_at'), table_name='agents')
    op.drop_table('agents')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created_at'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_audit_logs_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_target_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
